# Generated by go2rpm 1.18.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/sentriz/flagconf
%global goipath         github.com/sentriz/flagconf
Version:                0.1.9

%gometa -L -f

%global common_description %{expand:
Extensions to Go's flag package to support prefixed environment variables and a
simple config file format.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           flagconf
Release:        %autorelease
Summary:        Extensions to Go's flag package to support prefixed environment variables and a simple config file format

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

BuildRequires: golang(github.com/rogpeppe/go-internal)
BuildRequires: golang(golang.org/x/sys)
BuildRequires: golang(golang.org/x/tools)

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
